branch-defaults:
  chat:
    environment: ahmed-env
    group_suffix: null
  default:
    environment: null
    group_suffix: null
  develop:
    environment: ahmed-env
  master:
    environment: ahmed-env
deploy:
  artifact: target/websocket-0.0.1.war
global:
  application_name: websocket
  branch: null
  default_ec2_keyname: fares
  default_platform: Java 8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
