---
- hosts: all
  become: yes
  pre_tasks:
  - name: Ensure boto and boto3 are installed
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - python2-botocore
    - python2-boto3
  vars:
    javaver: 8u191
    javarpm: jdk-{{javaver}}-linux-x64.rpm
    bucket: mybucket
    tomuser: tomcat8
    tomver: 8.0.53
    tomarc: apache-tomcat-{{tomver}}.tar.gz
    tominstdir: /usr/local
  tasks:
  - name: Download java jdk {{javaver}}
#    get_url:
#      url: "{{javaurl}}"
#      dest: /tmp
#      headers: 
#        Cookie: oraclelicense=accept-securebackup-cookie
    aws_s3:
      mode: get
      bucket: "{{bucket}}"
      object: /java/{{javarpm}}
      dest: /tmp/{{javarpm}}
      overwrite: different
  - name: Install jdk {{javaver}}
    yum:
      name: /tmp/{{javarpm}}
      state: present
  - name: Create {{tomuser}} group
    group:
      name: "{{tomuser}}"
      state: present
  - name: Create {{tomuser}} user
    user: 
      name: "{{tomuser}}"
      home: "{{tominstdir}}/{{tomuser}}"
      createhome: no
      group: "{{tomuser}}"
      shell: /bin/nologin
      state: present
  - name: Download and install tomcat {{tomver}}
    unarchive:                                                                                                                                        
      src: https://archive.apache.org/dist/tomcat/tomcat-8/v{{tomver}}/bin/{{tomarc}}
      dest: "{{tominstdir}}"
      remote_src: yes      
      creates: "{{tominstdir}}/{{tomuser}}"
  - name: Rename unpacked archive to {{tomuser}}
    command: creates={{tominstdir}}/{{tomuser}} mv {{tominstdir}}/apache-tomcat-{{tomver}} {{tominstdir}}/{{tomuser}}
  - name: Set unpacked archive ownership to {{tomuser}}:{{tomuser}}
    file:
      path: "{{tominstdir}}/{{tomuser}}"
      owner: "{{tomuser}}"
      group: "{{tomuser}}"
      recurse: yes
  - name: Set group recursive read on tomcat conf dir
    file:
      path: "{{tominstdir}}/{{tomuser}}/conf"
      mode: g+r
      recurse: yes
  - name: Set group execute on tomcat conf dir
    file:
      path: "{{tominstdir}}/{{tomuser}}/conf"
      mode: g+x
  - name: install {{tomuser}} systemd unit file
    template:
      src: tomcat-unit.j2
      dest: /etc/systemd/system/{{tomuser}}.service
  - name: start service {{tomuser}}
    systemd:
      state: started
      name: "{{tomuser}}"
      daemon_reload: yes
  - name: rm /tmp/{{javarpm}}
    file:
      path: /tmp/{{javarpm}}
      state: absent
